Ojs\JournalBundle\Entity\MailTemplate:
    type: entity
    table: mail_template
    repositoryClass: Ojs\JournalBundle\Entity\MailTemplateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        journal:
          targetEntity: Ojs\JournalBundle\Entity\Journal
          joinColumn:
            name: journal_id
            referencedColumnName: id
        type:
          targetEntity: Ojs\JournalBundle\Entity\MailTemplateType
          joinColumn:
            name: type_id
    manyToMany:
        languages:
          targetEntity: Lang
          joinTable:
            inverseJoinColumns:
              language_id:
                referencedColumnName: id
            joinColumns:
              mailtemplate_id:
                referencedColumnName: id
            name: mail_template_language
          fetch: EXTRA_LAZY
    fields:
        lang:
            type: string
            length: 100
            column: lang
            gedmo:
                - versioned
        subject:
            type: string
            length: 100
            column: subject
            gedmo:
                - versioned
        template:
            type: text
            gedmo:
                - versioned
        created:
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        loggable: true
    lifecycleCallbacks: {  }
