<?php

namespace Ojs\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTemplateRepository extends EntityRepository
{
    public function findByTemplate($type, $lang)
    {
        $query = $this->createQueryBuilder('m')
            ->select('m.template')
            ->leftJoin('m.type', 't')
            ->andWhere('t.name = :type')
            ->andWhere('m.lang = :lang')
            ->setParameter('type', $type)
            ->setParameter('lang', $lang)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleScalarResult();
    }
}
